language: node_js

node_js:
  - 'node'

addons:
  code_climate:
    repo_token: f66214b3897dfe3beff2a9cd4825e07fe3e4b3a2510a11022a7b9f09ec5ba3c4

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm install codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
